services:
  backend:
    image: nobugsme/nbank:with_database_with_fix
    ports:
      - "4111:4111"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nbank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - nbank-network

  frontend:
    image: nobugsme/nbank-ui:with_nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nbank-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=nbank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - nbank-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d nbank" ]
      interval: 10s
      timeout: 5s
      retries: 5

  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: [ "-container-network", "nbank-network" ]
    environment:
      - DOCKER_API_VERSION=1.44
    depends_on:
      - frontend
    networks:
      - nbank-network
  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      - selenoid
    networks:
      - nbank-network

networks:
  nbank-network:
    name: nbank-network
    driver: bridge

volumes:
  postgres_data:
    driver: local